In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv

In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [3]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv

In [4]:
train = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')
test = pd.read_csv('/kaggle/input/digit-recognizer/test.csv')
sample = pd.read_csv('/kaggle/input/digit-recognizer/sample_submission.csv')

In [5]:
train

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
test

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
sample

       ImageId  Label
0            1      0
1            2      0
2            3      0
3            4      0
4            5      0
...        ...    ...
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

[28000 rows x 2 columns]

In [8]:
train.isnull().sum().sum(), test.isnull().sum().sum()

(0, 0)

In [9]:
ImageId = test.index + 1

y = train.iloc[:,0]
X = train.iloc[::,1:]
X_test = test

In [10]:
#the MNIST dataset has images with pixel values in the range [0, 255]
X = X / 255
X_test = X_test / 255

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=1)
X_train.shape, X_val.shape, y_train.shape, y_val.shape, X_test.shape

((37800, 784), (4200, 784), (37800,), (4200,), (28000, 784))

In [12]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(hidden_layer_sizes=(50, ), max_iter=50, alpha=1e-4, solver='sgd', verbose=10, random_state=1, learning_rate_init=.1).fit(X_train, y_train)
print(model.score(X_train, y_train))

Iteration 1, loss = 0.37729620
Iteration 2, loss = 0.18272482
Iteration 3, loss = 0.13783467
Iteration 4, loss = 0.11319304
Iteration 5, loss = 0.09221273
Iteration 6, loss = 0.08103465
Iteration 7, loss = 0.07042393
Iteration 8, loss = 0.06099312
Iteration 9, loss = 0.05428393
Iteration 10, loss = 0.04812538
Iteration 11, loss = 0.04182397
Iteration 12, loss = 0.03893636
Iteration 13, loss = 0.03255164
Iteration 14, loss = 0.03029009
Iteration 15, loss = 0.02715881
Iteration 16, loss = 0.02389699
Iteration 17, loss = 0.02007473
Iteration 18, loss = 0.01930541
Iteration 19, loss = 0.01584658
Iteration 20, loss = 0.01461953
Iteration 21, loss = 0.01218382
Iteration 22, loss = 0.01068126
Iteration 23, loss = 0.01070387
Iteration 24, loss = 0.00811611
Iteration 25, loss = 0.00679152
Iteration 26, loss = 0.00635826
Iteration 27, loss = 0.00532649
Iteration 28, loss = 0.00485012
Iteration 29, loss = 0.00424708
Iteration 30, loss = 0.00387652
Iteration 31, loss = 0.00348549
Iteration 32, loss = 0.00324371
Iteration 33, loss = 0.00301431
Iteration 34, loss = 0.00288992
Iteration 35, loss = 0.00268489
Iteration 36, loss = 0.00252577
Iteration 37, loss = 0.00239572
Iteration 38, loss = 0.00233056
Iteration 39, loss = 0.00219227
Iteration 40, loss = 0.00214445
Iteration 41, loss = 0.00205646
Iteration 42, loss = 0.00196314
Iteration 43, loss = 0.00189155
Iteration 44, loss = 0.00184093
Iteration 45, loss = 0.00177617
Iteration 46, loss = 0.00170776
Iteration 47, loss = 0.00168567
Iteration 48, loss = 0.00162692
Iteration 49, loss = 0.00158949
Iteration 50, loss = 0.00154174
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
1.0

In [13]:
y_pred = model.predict(X_val)
print(model.score(X_val, y_val))

0.9673809523809523

In [14]:
df_val=pd.DataFrame({'actual_value': y_val, 'predicted_value':y_pred})
df_val.reset_index(drop=True, inplace=True)
df_val

      actual_value  predicted_value
0                1                1
1                5                5
2                2                2
3                8                8
4                4                4
...            ...              ...
4195             0                0
4196             0                0
4197             4                4
4198             0                0
4199             0                0

[4200 rows x 2 columns]

In [15]:
prediction = model.predict(X_test)
prediction

array([2, 0, 9, ..., 3, 9, 2])

In [16]:
output = pd.DataFrame({'ImageId': ImageId, 'Label': prediction})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [17]:
#upload submission
submission = pd.read_csv("submission.csv")
submission

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]